-- Propiedad Configurable
go.property("gravedad", 1000)

function init(self)
	-- Inicializar Velocidad
	self.velocidad = vmath.vector3()
	self.quieto = false
end

function update(self, dt)
	-- Calcular Velocidad por Frame
	if not self.quieto then
		self.velocidad.y = self.velocidad.y - (self.gravedad * dt)
		local pos = go.get_position()
		pos = pos + self.velocidad * dt
		go.set_position(pos)
	end
end

function on_message(self, message_id, message, sender)
	-- Cuando un Cinemático choca contra un Estático Defold envía este mensaje
	if message_id == hash("contact_point_response") then
		self.quieto = true
	end	
end
