-- camara.script
go.property("sensibilidad", 0.3)
go.property("jugador", msg.url("/Jugador/Cuerpo"))
go.property("altura_camara", 2.0)

function init(self)
	self.rotacion_y = 0
	self.rotacion_x = 0 
	window.set_mouse_lock(true)
	msg.post(".", "acquire_input_focus")
end

function update(self, dt)
	-- Seguir jugador
	local posicion_jugador = go.get_position(self.jugador)
	posicion_jugador.y = posicion_jugador.y + self.altura_camara
	go.set_position(posicion_jugador)
	-- Rotacion basada en movimiento del mouse
	local q_rot_y = vmath.quat_rotation_y(math.rad(self.rotacion_y))
	local q_rot_x = vmath.quat_rotation_x(math.rad(self.rotacion_x))
	-- Sumar rotaciones
	go.set_rotation(q_rot_y * q_rot_x)
end

function on_input(self, action_id, action)
	-- Desbloquear mouse
	if action_id == hash("Esc") and action.released then
		window.set_mouse_lock(false)
	end
	-- Bloquear mouse
	if action_id == hash("LeftClick") and action.released then
		window.set_mouse_lock(true)
	end
	-- Mover camara
	if window.get_mouse_lock() and action.dx and action.dy then
		-- Vista horizontal
		self.rotacion_y = self.rotacion_y - (action.dx * self.sensibilidad)
		self.rotacion_x = self.rotacion_x + (action.dy * self.sensibilidad)
		-- Vista vertical
		self.rotacion_x = math.max(-80, math.min(80, self.rotacion_x))
	end
end
