go.property("velocidad", 5)
go.property("fuerza_salto", 6)
go.property("gravedad", -15)
go.property("camara", hash("/Jugador/Camara"))

function init(self)
	self.input_dir = vmath.vector3()
	self.velocidad_actual = vmath.vector3()
	self.correccion_colision = vmath.vector3()
	self.en_suelo = false
	self.normal_pared = vmath.vector3()
	msg.post(".", "acquire_input_focus")
end

function update(self, dt)
	-- Limpiar correccion en cada frame
	self.correccion_colision = vmath.vector3()
	-- Aplicar Gravedad 
	self.velocidad_actual.y = self.velocidad_actual.y + (self.gravedad * dt)
	-- Calcular direccion
	local direccion = vmath.vector3()
	if vmath.length_sqr(self.input_dir) > 0 then
		direccion = vmath.normalize(self.input_dir)
		local rotacion_camara_y = go.get(self.camara, "euler.y")
		local rotacion = vmath.quat_rotation_y(math.rad(rotacion_camara_y))
		direccion = vmath.rotate(rotacion, direccion)
	end
	-- Calcular velocidad horizontal buscada 
	local vel_x = direccion.x * self.velocidad
	local vel_z = direccion.z * self.velocidad
	-- Si estamos tocando una pared restamos desplazamiento antes de movernos
	if vmath.length_sqr(self.normal_pared) > 0 then
		local vector_horizontal = vmath.vector3(vel_x, 0, vel_z)
		local impacto = vmath.dot(vector_horizontal, self.normal_pared)
		if impacto < 0 then
			vector_horizontal = vector_horizontal - (self.normal_pared * impacto)
			vel_x = vector_horizontal.x
			vel_z = vector_horizontal.z
		end
	end
	-- Asignar la velocidad ya corregida (sin empujar muros)
	self.velocidad_actual.x = vel_x
	self.velocidad_actual.z = vel_z
	-- Mover al jugador 
	local posicion = go.get_position()
	go.set_position(posicion + (self.velocidad_actual * dt))
	-- Resetear 
	self.en_suelo = false
	self.normal_pared = vmath.vector3()
end

function on_message(self, message_id, message, sender)
	-- Colision Cinematica
	if message_id == hash("contact_point_response") then
		-- Empujar al jugador fuera 
		if message.distance > 0 then
			local proyeccion = vmath.project(self.correccion_colision, message.normal * message.distance)
			if proyeccion < 1 then
				local compensacion = (message.distance - message.distance * proyeccion) * message.normal
				go.set_position(go.get_position() + compensacion)
				self.correccion_colision = self.correccion_colision + compensacion
			end
		end
		-- Determinar si la superficie con la que chocamos apunta hacia arriba
		if message.normal.y > 0.7 then
			self.en_suelo = true
			--self.velocidad_actual.y = 0 
		elseif math.abs(message.normal.y) < 0.2 then
			-- Guardamos direccion de pared
			self.normal_pared = message.normal
		end
		-- Calculo de velocidad frente al obstaculo
		local impacto_velocidad = vmath.dot(self.velocidad_actual, message.normal)
		if impacto_velocidad < 0 then
			self.velocidad_actual = self.velocidad_actual - (message.normal * impacto_velocidad)
		end
	elseif message_id == hash("trigger_response") then
		print(message.other_id)
		go.delete(message.other_id)
	end
end

function on_input(self, action_id, action)
	-- Leer teclas directamente (W, A, S, D, Espacio)
	if action_id == hash("Adelante") then
		self.input_dir.z = action.released and 0 or -1
	elseif action_id == hash("Atras") then
		self.input_dir.z = action.released and 0 or 1
	elseif action_id == hash("Izquierda") then
		self.input_dir.x = action.released and 0 or -1
	elseif action_id == hash("Derecha") then
		self.input_dir.x = action.released and 0 or 1
	elseif action_id == hash("Saltar") and self.en_suelo then
		if action.pressed then
			self.velocidad_actual.y = self.fuerza_salto
		end
	end
end
