go.property("velocidad_movimiento", 5)
go.property("fuerza_salto", 8)
go.property("gravedad", -20)

function init(self)
	msg.post(".", "acquire_input_focus")

	self.input_dir = vmath.vector3()
	self.velocidad_y = 0
	self.en_suelo = false
	self.correccion = vmath.vector3()
	self.temporizador_suelo = 0
end

function update(self, dt)
	-- 1. Movimiento Vertical
	if self.en_suelo then
		self.velocidad_y = -0.5 
	else
		self.velocidad_y = self.velocidad_y + (self.gravedad * dt)
	end
	-- 2. Movimiento horizontal
	local dir = vmath.vector3(self.input_dir.x, 0, self.input_dir.z)
	if vmath.length(dir) > 1 then 
		dir = vmath.normalize(dir) 
	end
	-- 3. Calculo de Movimiento
	local pos_actual = go.get_position()
	pos_actual = pos_actual + (dir * self.velocidad_movimiento * dt)
	pos_actual.y = pos_actual.y + (self.velocidad_y * dt)
	go.set_position(pos_actual)
	-- 4. Resetear estado
	self.input_dir.x = 0
	self.input_dir.z = 0
	self.correccion = vmath.vector3()
	if self.temporizador_suelo > 0 then
		self.temporizador_suelo = self.temporizador_suelo - dt
		self.en_suelo = true
	else
		self.en_suelo = false
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") then
		if message.distance > 0 then
			-- Separar al jugador para que no atraviese paredes/suelo
			local proyeccion = vmath.dot(self.correccion, message.normal)
			local compensacion = (message.distance - proyeccion) * message.normal
			self.correccion = self.correccion + compensacion
			go.set_position(go.get_position() + compensacion)

			if message.normal.y > 0.7 then
				self.temporizador_suelo = 0.15 
			end
		end
	end
end

function on_input(self, action_id, action)
	if action_id == hash("Adelante") then self.input_dir.z = -1
	elseif action_id == hash("Atras") then self.input_dir.z = 1
	elseif action_id == hash("Izquierda") then self.input_dir.x = -1
	elseif action_id == hash("Derecha") then self.input_dir.x = 1
	end

	if action_id == hash("Saltar") and action.pressed and self.en_suelo then
		self.velocidad_y = self.fuerza_salto
		self.temporizador_suelo = 0
		self.en_suelo = false
	end
end
